#requires -Version 7.0

<#
.SYNOPSIS
    Post-processes PlatyPS-generated markdown help files.

.DESCRIPTION
    Runs after './build.ps1 -Tasks docs' to clean up common PlatyPS artifacts:

    - Replaces the '{{ Fill ProgressAction Description }}' placeholder with a
      standard description.
    - Populates empty RELATED LINKS sections with the project GitHub URL and
      website.
    - Reports a summary of changes made.

    Designed to be run from the repository root.

.PARAMETER DocsPath
    Path to the PlatyPS markdown help folder. Defaults to 'docs/en-US'.

.PARAMETER GitHubUrl
    GitHub repository URL. Auto-detected from 'gh repo view' if not provided.

.PARAMETER WebsiteUrl
    Project or author website URL. Defaults to 'https://christaylor.codes'.

.EXAMPLE
    # Auto-detect everything
    ./Scripts/Update-PlatyPSDocs.ps1

.EXAMPLE
    # Explicit paths
    ./Scripts/Update-PlatyPSDocs.ps1 -DocsPath 'docs/en-US' -GitHubUrl 'https://github.com/christaylorcodes/PSSonicOS'
#>
[CmdletBinding()]
param(
    [Parameter()]
    [string]$DocsPath = 'docs/en-US',

    [Parameter()]
    [string]$GitHubUrl,

    [Parameter()]
    [string]$WebsiteUrl = 'https://christaylor.codes'
)

$ErrorActionPreference = 'Stop'

# Resolve docs path
if (-not (Test-Path $DocsPath)) {
    Write-Error "Docs path '$DocsPath' not found. Run './build.ps1 -Tasks docs' first."
    return
}

# Auto-detect GitHub URL if not provided
if (-not $GitHubUrl) {
    try {
        $GitHubUrl = (gh repo view --json url | ConvertFrom-Json).url
        Write-Verbose "Auto-detected GitHub URL: $GitHubUrl"
    }
    catch {
        Write-Warning 'Could not auto-detect GitHub URL. RELATED LINKS will not be updated.'
    }
}

$ProgressActionDescription = 'Determines how the cmdlet responds to progress updates generated by a command. See the ProgressAction common parameter for more information.'

$files = Get-ChildItem -Path $DocsPath -Filter '*.md' -File
$stats = @{
    ProgressAction = 0
    RelatedLinks   = 0
    TotalFiles     = $files.Count
}

foreach ($file in $files) {
    $content = Get-Content -Path $file.FullName -Raw
    $modified = $false

    # Replace ProgressAction placeholder
    if ($content -match '\{\{ Fill ProgressAction Description \}\}') {
        $content = $content -replace '\{\{ Fill ProgressAction Description \}\}', $ProgressActionDescription
        $modified = $true
        $stats.ProgressAction++
    }

    # Populate empty RELATED LINKS
    if ($GitHubUrl -and $content -match '(?m)^## RELATED LINKS\s*$') {
        $linksBlock = @"
## RELATED LINKS

[$GitHubUrl]($GitHubUrl)

[$WebsiteUrl]($WebsiteUrl)
"@
        $content = $content -replace '(?m)^## RELATED LINKS\s*$', $linksBlock
        $modified = $true
        $stats.RelatedLinks++
    }

    if ($modified) {
        Set-Content -Path $file.FullName -Value $content -NoNewline -Encoding utf8
    }
}

Write-Host "Updated $($stats.TotalFiles) docs in '$DocsPath':" -ForegroundColor Cyan
Write-Host "  ProgressAction placeholders fixed: $($stats.ProgressAction)" -ForegroundColor Green
Write-Host "  RELATED LINKS populated:           $($stats.RelatedLinks)" -ForegroundColor Green
